# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beba44c3d1a1091613390cfff3d040d5755267992d704928682801b6363e814c9c2070cde64b98d2b5f857fef7d7ee4330e0bf5ecf2aefdf5734f4dfb95fa2e0

test:
  secret_key_base: 80471e5cfd48946f0c3d36e3e34fde2c0efe00b565d031362a39b969ca901f47c227b1235950f8d14f03266332210e6959c61c4eb651aeafd41c8a445862e3ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
